/**
 * @file inference.c
 * @brief TFLite Micro inference for encoder and policy on ESP32-S3.
 *
 * Uses the C headers generated by quantize_export.py.
 * Two separate interpreters: one for the encoder, one for the policy.
 */
#include "inference.h"
#include "image_proc.h"
#include "esp_log.h"

#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/schema/schema_generated.h"

/*
 * Model data embedded as C arrays.
 * These are generated by quantize_export.py → tflite_to_c_header().
 * Uncomment the includes once models are exported.
 */
/* #include "encoder_model.h" */
/* #include "policy_model.h" */

/* Placeholder model data — replace with actual includes above */
static const uint8_t encoder_model[] = {0};
static const unsigned int encoder_model_len = 0;
static const uint8_t policy_model[] = {0};
static const unsigned int policy_model_len = 0;

static const char *TAG = "inference";

/* ── TFLite Micro state ── */

static uint8_t encoder_arena[TFLITE_ARENA_SIZE] __attribute__((aligned(16)));
static uint8_t policy_arena[16 * 1024] __attribute__((aligned(16)));

static tflite::MicroInterpreter *encoder_interp = nullptr;
static tflite::MicroInterpreter *policy_interp = nullptr;

/* Op resolver — add only the ops used by our models */
static tflite::MicroMutableOpResolver<10> resolver;

static bool s_initialized = false;

esp_err_t inference_init(void)
{
    if (s_initialized) return ESP_OK;

    ESP_LOGI(TAG, "Initializing TFLite Micro...");
    ESP_LOGI(TAG, "Encoder model: %u bytes", encoder_model_len);
    ESP_LOGI(TAG, "Policy model:  %u bytes", policy_model_len);

    if (encoder_model_len == 0 || policy_model_len == 0) {
        ESP_LOGW(TAG, "Model data not embedded yet — using placeholder.");
        ESP_LOGW(TAG, "Export models with quantize_export.py and include the .h files.");
        return ESP_ERR_NOT_FOUND;
    }

    /* Register ops used by TinyEncoder + TinyPolicy */
    resolver.AddConv2D();
    resolver.AddDepthwiseConv2D();
    resolver.AddRelu();
    resolver.AddReshape();
    resolver.AddFullyConnected();
    resolver.AddQuantize();
    resolver.AddDequantize();
    resolver.AddMean();          /* for batch norm folded layers */
    resolver.AddAdd();           /* for residual-like connections */
    resolver.AddSoftmax();

    /* ── Encoder interpreter ── */
    const tflite::Model *enc_model = tflite::GetModel(encoder_model);
    if (enc_model == nullptr) {
        ESP_LOGE(TAG, "Failed to load encoder model");
        return ESP_FAIL;
    }

    static tflite::MicroInterpreter enc_interpreter(
        enc_model, resolver, encoder_arena, TFLITE_ARENA_SIZE);
    if (enc_interpreter.AllocateTensors() != kTfLiteOk) {
        ESP_LOGE(TAG, "Encoder AllocateTensors failed");
        return ESP_FAIL;
    }
    encoder_interp = &enc_interpreter;

    ESP_LOGI(TAG, "Encoder arena used: %zu / %d bytes",
             enc_interpreter.arena_used_bytes(), TFLITE_ARENA_SIZE);

    /* ── Policy interpreter ── */
    const tflite::Model *pol_model = tflite::GetModel(policy_model);
    if (pol_model == nullptr) {
        ESP_LOGE(TAG, "Failed to load policy model");
        return ESP_FAIL;
    }

    static tflite::MicroInterpreter pol_interpreter(
        pol_model, resolver, policy_arena, sizeof(policy_arena));
    if (pol_interpreter.AllocateTensors() != kTfLiteOk) {
        ESP_LOGE(TAG, "Policy AllocateTensors failed");
        return ESP_FAIL;
    }
    policy_interp = &pol_interpreter;

    ESP_LOGI(TAG, "Policy arena used: %zu / %zu bytes",
             pol_interpreter.arena_used_bytes(), sizeof(policy_arena));

    s_initialized = true;
    ESP_LOGI(TAG, "TFLite Micro ready.");
    return ESP_OK;
}

esp_err_t inference_run_encoder(const uint8_t *img_rgb888, int8_t *features)
{
    if (!s_initialized || encoder_interp == nullptr) {
        return ESP_ERR_INVALID_STATE;
    }

    TfLiteTensor *input = encoder_interp->input(0);

    /* Convert uint8 image [0,255] to int8 [-128,127] */
    const int total = IMG_TARGET_SIZE;  /* 48*48*3 = 6912 */
    int8_t *in_data = input->data.int8;
    for (int i = 0; i < total; i++) {
        in_data[i] = (int8_t)((int16_t)img_rgb888[i] - 128);
    }

    /* Run inference */
    if (encoder_interp->Invoke() != kTfLiteOk) {
        ESP_LOGE(TAG, "Encoder invoke failed");
        return ESP_FAIL;
    }

    /* Copy output features: 3x3x32 = 288 int8 values */
    TfLiteTensor *output = encoder_interp->output(0);
    memcpy(features, output->data.int8, CORR_FEAT_SIZE);

    return ESP_OK;
}

esp_err_t inference_run_policy(const int8_t *corr_cue, int8_t *action_logits)
{
    if (!s_initialized || policy_interp == nullptr) {
        return ESP_ERR_INVALID_STATE;
    }

    TfLiteTensor *input = policy_interp->input(0);
    memcpy(input->data.int8, corr_cue, CORR_CUE_SIZE);

    if (policy_interp->Invoke() != kTfLiteOk) {
        ESP_LOGE(TAG, "Policy invoke failed");
        return ESP_FAIL;
    }

    TfLiteTensor *output = policy_interp->output(0);
    memcpy(action_logits, output->data.int8, 4);

    return ESP_OK;
}

int inference_argmax_i8(const int8_t *arr, int len)
{
    int best_idx = 0;
    int8_t best_val = arr[0];
    for (int i = 1; i < len; i++) {
        if (arr[i] > best_val) {
            best_val = arr[i];
            best_idx = i;
        }
    }
    return best_idx;
}
