/**
 * @file inference.cpp
 * @brief TFLite Micro — encoder-only inference on Camera Board.
 *
 * The Camera Board runs ONLY the encoder: 48x48 RGB → 3x3x32 features.
 * Features are sent to Motor Board via SPI for correlation + policy.
 *
 * Uses the C header generated by quantize_export.py.
 */
#include "inference.h"
#include "image_proc.h"
#include "esp_log.h"

#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/schema/schema_generated.h"

/*
 * Model data embedded as C array.
 * Generated by quantize_export.py → tflite_to_c_header().
 * Uncomment the include once model is exported.
 */
/* #include "encoder_model.h" */

/* Placeholder model data — replace with actual include above */
static const uint8_t encoder_model[] = {0};
static const unsigned int encoder_model_len = 0;

static const char *TAG = "inference";

/* TFLite Micro state */
#define ENCODER_ARENA_SIZE  (80 * 1024)   /* 80 KB */
static uint8_t encoder_arena[ENCODER_ARENA_SIZE] __attribute__((aligned(16)));
static tflite::MicroInterpreter *encoder_interp = nullptr;
static tflite::MicroMutableOpResolver<8> resolver;
static bool s_initialized = false;

esp_err_t inference_init(void)
{
    if (s_initialized) return ESP_OK;

    ESP_LOGI(TAG, "Initializing encoder TFLite Micro...");
    ESP_LOGI(TAG, "Encoder model: %u bytes", encoder_model_len);

    if (encoder_model_len == 0) {
        ESP_LOGW(TAG, "Encoder model not embedded yet — using placeholder.");
        ESP_LOGW(TAG, "Export with quantize_export.py and include encoder_model.h");
        return ESP_ERR_NOT_FOUND;
    }

    /* Register ops used by TinyEncoder */
    resolver.AddConv2D();
    resolver.AddDepthwiseConv2D();
    resolver.AddRelu();
    resolver.AddReshape();
    resolver.AddQuantize();
    resolver.AddDequantize();
    resolver.AddMean();
    resolver.AddAdd();

    const tflite::Model *model = tflite::GetModel(encoder_model);
    if (model == nullptr) {
        ESP_LOGE(TAG, "Failed to load encoder model");
        return ESP_FAIL;
    }

    static tflite::MicroInterpreter interpreter(
        model, resolver, encoder_arena, ENCODER_ARENA_SIZE);
    if (interpreter.AllocateTensors() != kTfLiteOk) {
        ESP_LOGE(TAG, "Encoder AllocateTensors failed");
        return ESP_FAIL;
    }
    encoder_interp = &interpreter;

    ESP_LOGI(TAG, "Encoder arena used: %zu / %d bytes",
             interpreter.arena_used_bytes(), ENCODER_ARENA_SIZE);

    s_initialized = true;
    ESP_LOGI(TAG, "Encoder TFLite Micro ready.");
    return ESP_OK;
}

esp_err_t inference_run_encoder(const uint8_t *img_rgb888, int8_t *features)
{
    if (!s_initialized || encoder_interp == nullptr) {
        return ESP_ERR_INVALID_STATE;
    }

    TfLiteTensor *input = encoder_interp->input(0);

    /* Convert uint8 image [0,255] to int8 [-128,127] */
    const int total = IMG_TARGET_SIZE;  /* 48*48*3 = 6912 */
    int8_t *in_data = input->data.int8;
    for (int i = 0; i < total; i++) {
        in_data[i] = (int8_t)((int16_t)img_rgb888[i] - 128);
    }

    if (encoder_interp->Invoke() != kTfLiteOk) {
        ESP_LOGE(TAG, "Encoder invoke failed");
        return ESP_FAIL;
    }

    /* Copy output: 3x3x32 = 288 int8 values */
    TfLiteTensor *output = encoder_interp->output(0);
    memcpy(features, output->data.int8, 288);

    return ESP_OK;
}

/* Not used on Camera Board — policy runs on Motor Board */
esp_err_t inference_run_policy(const int8_t *corr_cue, int8_t *action_logits)
{
    (void)corr_cue;
    (void)action_logits;
    ESP_LOGE(TAG, "Policy inference not available on Camera Board");
    return ESP_ERR_NOT_SUPPORTED;
}

int inference_argmax_i8(const int8_t *arr, int len)
{
    int best_idx = 0;
    int8_t best_val = arr[0];
    for (int i = 1; i < len; i++) {
        if (arr[i] > best_val) {
            best_val = arr[i];
            best_idx = i;
        }
    }
    return best_idx;
}
