/**
 * @file inference.cpp
 * @brief TFLite Micro — policy-only inference on Motor Board.
 *
 * The Motor Board runs the policy MLP: 83-dim correlation cue → 4 action logits.
 * Encoder features arrive from Camera Board via SPI; correlation is done in plain C.
 */
#include "inference.h"
#include "esp_log.h"

#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/schema/schema_generated.h"

/*
 * Policy model embedded as C array.
 * Generated by quantize_export.py → tflite_to_c_header().
 * Uncomment the include once model is exported.
 */
/* #include "policy_model.h" */

/* Placeholder — replace with actual include above */
static const uint8_t policy_model[] = {0};
static const unsigned int policy_model_len = 0;

static const char *TAG = "inference";

/* TFLite Micro state */
static uint8_t policy_arena[TFLITE_ARENA_SIZE] __attribute__((aligned(16)));
static tflite::MicroInterpreter *policy_interp = nullptr;
static tflite::MicroMutableOpResolver<4> resolver;
static bool s_initialized = false;

esp_err_t inference_init(void)
{
    if (s_initialized) return ESP_OK;

    ESP_LOGI(TAG, "Initializing policy TFLite Micro...");
    ESP_LOGI(TAG, "Policy model: %u bytes", policy_model_len);

    if (policy_model_len == 0) {
        ESP_LOGW(TAG, "Policy model not embedded yet — using placeholder.");
        ESP_LOGW(TAG, "Export with quantize_export.py and include policy_model.h");
        return ESP_ERR_NOT_FOUND;
    }

    /* Register ops used by TinyPolicy (3 FC layers + ReLU) */
    resolver.AddFullyConnected();
    resolver.AddRelu();
    resolver.AddQuantize();
    resolver.AddDequantize();

    const tflite::Model *model = tflite::GetModel(policy_model);
    if (model == nullptr) {
        ESP_LOGE(TAG, "Failed to load policy model");
        return ESP_FAIL;
    }

    static tflite::MicroInterpreter interpreter(
        model, resolver, policy_arena, TFLITE_ARENA_SIZE);
    if (interpreter.AllocateTensors() != kTfLiteOk) {
        ESP_LOGE(TAG, "Policy AllocateTensors failed");
        return ESP_FAIL;
    }
    policy_interp = &interpreter;

    ESP_LOGI(TAG, "Policy arena used: %zu / %d bytes",
             interpreter.arena_used_bytes(), TFLITE_ARENA_SIZE);

    s_initialized = true;
    ESP_LOGI(TAG, "Policy TFLite Micro ready.");
    return ESP_OK;
}

esp_err_t inference_run_policy(const int8_t *corr_cue, int8_t *action_logits)
{
    if (!s_initialized || policy_interp == nullptr) {
        return ESP_ERR_INVALID_STATE;
    }

    TfLiteTensor *input = policy_interp->input(0);
    memcpy(input->data.int8, corr_cue, CORR_CUE_SIZE);

    if (policy_interp->Invoke() != kTfLiteOk) {
        ESP_LOGE(TAG, "Policy invoke failed");
        return ESP_FAIL;
    }

    TfLiteTensor *output = policy_interp->output(0);
    memcpy(action_logits, output->data.int8, 4);

    return ESP_OK;
}

int inference_argmax_i8(const int8_t *arr, int len)
{
    int best_idx = 0;
    int8_t best_val = arr[0];
    for (int i = 1; i < len; i++) {
        if (arr[i] > best_val) {
            best_val = arr[i];
            best_idx = i;
        }
    }
    return best_idx;
}
