#!/usr/bin/env python3
"""
train_depth_guard.py — Phase 1: Train tiny obstacle detector for ESP32 Camera Board.

Distills MiDaS depth knowledge into a binary classifier:
  Input:  48×48 RGB image
  Output: obstacle probability (0=far, 1=close)

The model answers one question: "Is there a wall/obstacle within ~30cm ahead?"
This replaces the ultrasonic sensor for collision avoidance during exploration.

Pipeline:
  1. Run MiDaS on existing images → extract min depth in center strip
  2. Label: depth < threshold → blocked (1), else clear (0)
  3. Train tiny 3-layer CNN → sigmoid
  4. Export to TFLite INT8
"""

import os
import glob
import time

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, random_split
from PIL import Image

# ═══════════════════════════════════════════════
#  Configuration
# ═══════════════════════════════════════════════
DATA_DIR           = "data"              # root with session subdirs containing images/
DEPTH_DIR          = "data"              # MiDaS depth maps (generated by gen_depth.py)
OUTPUT_DIR         = "./checkpoints/depth_guard"
IMG_SIZE           = 48
DEVICE             = "cuda" if torch.cuda.is_available() else "cpu"

# Depth labeling
CENTER_STRIP_FRAC  = 0.4      # fraction of image width to consider as "ahead"
OBSTACLE_THRESHOLD = 0.7      # MiDaS depth > this (inverted: high = close) → blocked
BALANCE_WEIGHT     = True     # up-weight minority class

# Model
HIDDEN_CHANNELS    = [16, 32, 32]

# Training
LR                 = 1e-3
BATCH_SIZE         = 64
EPOCHS             = 50
VAL_SPLIT          = 0.15
SEED               = 42
# ═══════════════════════════════════════════════


class DepthGuardCNN(nn.Module):
    """
    Tiny CNN binary classifier for obstacle detection.

    Input:  (B, 3, 48, 48) RGB image
    Output: (B, 1) obstacle probability

    Architecture: 3 conv layers → global avg pool → sigmoid
    ~10K parameters → ~12KB INT8
    """

    def __init__(self, channels=None):
        super().__init__()
        if channels is None:
            channels = HIDDEN_CHANNELS

        self.features = nn.Sequential(
            # 48×48 → 24×24
            nn.Conv2d(3, channels[0], 3, stride=2, padding=1, bias=False),
            nn.BatchNorm2d(channels[0]),
            nn.ReLU(inplace=True),

            # 24×24 → 12×12
            nn.Conv2d(channels[0], channels[1], 3, stride=2, padding=1, bias=False),
            nn.BatchNorm2d(channels[1]),
            nn.ReLU(inplace=True),

            # 12×12 → 6×6
            nn.Conv2d(channels[1], channels[2], 3, stride=2, padding=1, bias=False),
            nn.BatchNorm2d(channels[2]),
            nn.ReLU(inplace=True),
        )

        self.classifier = nn.Sequential(
            nn.AdaptiveAvgPool2d(1),  # 6×6 → 1×1
            nn.Flatten(),
            nn.Linear(channels[2], 1),
        )

    def forward(self, x):
        x = self.features(x)
        return self.classifier(x)  # (B, 1) raw logit

    def predict(self, x):
        """Returns probability of obstacle (0–1)."""
        return torch.sigmoid(self.forward(x))

    def count_params(self):
        return sum(p.numel() for p in self.parameters())


# ─── Dataset ───

def discover_images_and_depths(data_root):
    """
    Find all (image, depth) pairs across session directories.

    Expected structure:
        data/session_name/images/frame_000000.jpg
        data/session_name/depth/frame_000000.npy
    """
    pairs = []

    for session in sorted(os.listdir(data_root)):
        img_dir = os.path.join(data_root, session, "images")
        depth_dir = os.path.join(data_root, session, "depth")

        if not os.path.isdir(img_dir) or not os.path.isdir(depth_dir):
            continue

        for img_file in sorted(glob.glob(os.path.join(img_dir, "*.jpg"))):
            basename = os.path.splitext(os.path.basename(img_file))[0]
            depth_file = os.path.join(depth_dir, f"{basename}.npy")

            if os.path.exists(depth_file):
                pairs.append((img_file, depth_file))

    print(f"[DepthGuard] Found {len(pairs)} image-depth pairs")
    return pairs


def label_from_depth(depth_map, center_frac=CENTER_STRIP_FRAC,
                     threshold=OBSTACLE_THRESHOLD):
    """
    Label an image as blocked/clear based on MiDaS depth map.

    MiDaS depth is inverted: high values = close objects.
    We check the center strip of the image (where the robot drives toward).

    Args:
        depth_map: (H, W) float32 normalized [0, 1]
        center_frac: fraction of width to consider as center strip
        threshold: if max depth in center strip > this → blocked

    Returns:
        1.0 if blocked, 0.0 if clear
    """
    h, w = depth_map.shape
    margin = int(w * (1 - center_frac) / 2)
    center = depth_map[:, margin:w - margin]

    # Check bottom half of center strip (closer to robot)
    bottom_half = center[h // 2:, :]

    # If the maximum depth value in the bottom-center exceeds threshold → obstacle
    max_depth = np.max(bottom_half) if bottom_half.size > 0 else 0.0
    return 1.0 if max_depth > threshold else 0.0


class DepthGuardDataset(Dataset):
    """Dataset for depth guard training."""

    def __init__(self, pairs, augment=True):
        self.pairs = pairs
        self.augment = augment

        # Pre-compute labels
        self.labels = []
        blocked_count = 0
        for _, depth_path in pairs:
            depth = np.load(depth_path)
            label = label_from_depth(depth)
            self.labels.append(label)
            blocked_count += int(label)

        self.blocked_ratio = blocked_count / max(len(pairs), 1)
        print(f"[DepthGuard] Labels: {blocked_count} blocked / "
              f"{len(pairs) - blocked_count} clear "
              f"({self.blocked_ratio:.1%} blocked)")

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, idx):
        img_path, _ = self.pairs[idx]
        label = self.labels[idx]

        img = Image.open(img_path).convert("RGB")
        if img.size != (IMG_SIZE, IMG_SIZE):
            img = img.resize((IMG_SIZE, IMG_SIZE), Image.LANCZOS)
        arr = np.array(img, dtype=np.float32) / 255.0

        if self.augment:
            # Random brightness
            if np.random.random() < 0.5:
                factor = np.random.uniform(0.7, 1.3)
                arr = np.clip(arr * factor, 0, 1)

            # Random horizontal flip (doesn't change center strip label)
            if np.random.random() < 0.5:
                arr = arr[:, ::-1, :].copy()

        tensor = torch.from_numpy(arr).permute(2, 0, 1)  # (3, H, W)
        return tensor, torch.tensor([label], dtype=torch.float32)


# ─── Training ───

def train_epoch(model, loader, optimizer, criterion, device, pos_weight=None):
    model.train()
    total_loss = 0
    correct = 0
    total = 0

    for imgs, labels in loader:
        imgs, labels = imgs.to(device), labels.to(device)

        logits = model(imgs)
        loss = criterion(logits, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item() * len(imgs)
        preds = (torch.sigmoid(logits) > 0.5).float()
        correct += (preds == labels).sum().item()
        total += len(imgs)

    return total_loss / total, correct / total


@torch.no_grad()
def eval_epoch(model, loader, criterion, device):
    model.eval()
    total_loss = 0
    correct = 0
    total = 0
    tp = fp = tn = fn = 0

    for imgs, labels in loader:
        imgs, labels = imgs.to(device), labels.to(device)

        logits = model(imgs)
        loss = criterion(logits, labels)

        total_loss += loss.item() * len(imgs)
        preds = (torch.sigmoid(logits) > 0.5).float()
        correct += (preds == labels).sum().item()
        total += len(imgs)

        tp += ((preds == 1) & (labels == 1)).sum().item()
        fp += ((preds == 1) & (labels == 0)).sum().item()
        tn += ((preds == 0) & (labels == 0)).sum().item()
        fn += ((preds == 0) & (labels == 1)).sum().item()

    acc = correct / max(total, 1)
    precision = tp / max(tp + fp, 1)
    recall = tp / max(tp + fn, 1)
    f1 = 2 * precision * recall / max(precision + recall, 1e-8)

    return total_loss / max(total, 1), acc, precision, recall, f1


def export_tflite(model, output_path, img_size=48):
    """Export model to TFLite INT8 via ONNX."""
    import onnx

    model.eval().cpu()
    dummy = torch.randn(1, 3, img_size, img_size)

    onnx_path = output_path.replace(".tflite", ".onnx")
    torch.onnx.export(
        model, dummy, onnx_path,
        input_names=["image"],
        output_names=["logit"],
        opset_version=13,
        dynamic_axes=None,
    )
    print(f"[Export] ONNX saved: {onnx_path}")

    # Note: TFLite conversion requires tf/onnx2tf installed
    # For now, save the ONNX — convert manually or via quantize_export.py
    print(f"[Export] Convert to TFLite with:")
    print(f"  python -m onnxruntime.transformers.onnx2tf {onnx_path}")

    return onnx_path


def main():
    print("=" * 55)
    print("  Phase 1: Depth Guard Training")
    print(f"  Device: {DEVICE}")
    print("=" * 55)

    torch.manual_seed(SEED)
    np.random.seed(SEED)
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    # Discover data
    pairs = discover_images_and_depths(DATA_DIR)
    if len(pairs) == 0:
        print("\n[ERROR] No image-depth pairs found.")
        print("Run gen_depth.py first to generate MiDaS depth maps.")
        return

    # Create dataset
    full_ds = DepthGuardDataset(pairs, augment=True)

    # Split
    val_size = int(len(full_ds) * VAL_SPLIT)
    train_size = len(full_ds) - val_size
    train_ds, val_ds = random_split(full_ds, [train_size, val_size])

    # Disable augmentation for validation
    val_ds_no_aug = DepthGuardDataset(
        [pairs[i] for i in val_ds.indices], augment=False
    )

    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE,
                              shuffle=True, num_workers=2)
    val_loader = DataLoader(val_ds_no_aug, batch_size=BATCH_SIZE,
                            shuffle=False, num_workers=2)

    # Model
    device = torch.device(DEVICE)
    model = DepthGuardCNN().to(device)
    print(f"\n[*] Model: {model.count_params()} parameters")

    # Class-balanced loss
    pos_weight = None
    if BALANCE_WEIGHT and full_ds.blocked_ratio > 0:
        pw = (1.0 - full_ds.blocked_ratio) / full_ds.blocked_ratio
        pos_weight = torch.tensor([pw], device=device)
        print(f"[*] Positive weight: {pw:.2f}")

    criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
    optimizer = torch.optim.Adam(model.parameters(), lr=LR)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, EPOCHS)

    # Training loop
    best_f1 = 0.0
    print(f"\n[*] Training for {EPOCHS} epochs\n")

    for epoch in range(1, EPOCHS + 1):
        t0 = time.time()
        train_loss, train_acc = train_epoch(
            model, train_loader, optimizer, criterion, device
        )
        val_loss, val_acc, prec, rec, f1 = eval_epoch(
            model, val_loader, criterion, device
        )
        scheduler.step()
        dt = time.time() - t0

        print(f"Epoch {epoch:>3}/{EPOCHS} | "
              f"TrLoss={train_loss:.4f} TrAcc={train_acc:.3f} | "
              f"VlLoss={val_loss:.4f} VlAcc={val_acc:.3f} | "
              f"P={prec:.3f} R={rec:.3f} F1={f1:.3f} | "
              f"{dt:.1f}s")

        if f1 > best_f1:
            best_f1 = f1
            torch.save(model.state_dict(),
                       os.path.join(OUTPUT_DIR, "best.pt"))
            print(f"  >> New best F1={f1:.3f}, saved!")

    # Final save
    torch.save(model.state_dict(),
               os.path.join(OUTPUT_DIR, "final.pt"))

    # Export ONNX
    model.load_state_dict(
        torch.load(os.path.join(OUTPUT_DIR, "best.pt"),
                   map_location="cpu", weights_only=True)
    )
    export_tflite(model, os.path.join(OUTPUT_DIR, "depth_guard.tflite"))

    print(f"\n{'='*55}")
    print(f"  Training complete!")
    print(f"  Best F1: {best_f1:.3f}")
    print(f"  Checkpoints: {OUTPUT_DIR}")
    print(f"{'='*55}")


if __name__ == "__main__":
    main()
